<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 20 Dec 2022 23:07:37 +0000
 */

$conf['title'] = 'Энциклопедия';
$conf['lang'] = 'ru';
$conf['template'] = 'nomadjimbob-mikio-279ad03';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['proxy']['user'] = 'altushka';
$conf['proxy']['pass'] = '<b>bGVnODkxNTc1MDMwMTA=';
$conf['tpl']['nomadjimbob-mikio-279ad03']['useLESS'] = 0;
$conf['tpl']['nomadjimbob-mikio-279ad03']['showLightDark'] = 1;
$conf['tpl']['nomadjimbob-mikio-279ad03']['sidebarAlwaysShowLeft'] = 1;
$conf['tpl']['nomadjimbob-mikio-279ad03']['sidebarAlwaysShowRight'] = 1;
$conf['tpl']['MindTheDark-2022-11-20']['theme'] = 'dark';
$conf['tpl']['MindTheDark-2022-11-20']['autoDark'] = '1';
$conf['tpl']['MindTheDark-2022-11-20']['userChoice'] = '1';
$conf['tpl']['MindTheDark-2022-11-20']['pluginNote'] = '1';
$conf['tpl']['MindTheDark-2022-11-20']['pluginWrap'] = '1';
