<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Tue, 20 Dec 2022 22:04:39 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
