# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 20 Dec 2022 22:04:39 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$edj181hH5J8t9RP4zouKrOf1WzjQ4F5MWU5YpnCtUdSm.dfzhRt4W:admin:egunovzahar2006@gmail.com:admin,user
